insert into microservices.inventory values('choco','us',67,10);
insert into microservices.inventory values('COKE','SouthZone',23,20);
insert into microservices.inventory values('DAIRYMILK','SouthZone',67,20);
insert into microservices.inventory values('fan','india',67,30);
insert into microservices.inventory values('MAZZA','SouthZone',67,20);
insert into microservices.inventory values('MilkBikies','SouthZone',67,50);
insert into microservices.inventory values('OREO','SouthZone',67,20);
insert into microservices.inventory values('Snickers','SouthZone',67,20);
insert into microservices.inventory values('SPRITE','SouthZone',67,30);